# Generated by Django 3.0.4 on 2020-03-25 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('farmer_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('company_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comment', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Company')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transactions.Farmer')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
